import { ErrorHandler } from '@angular/core';
import { DatadogService } from './datadog.service';

// code generated by github copilot
export class AppErrorHandler implements ErrorHandler {

  constructor(private _datadog: DatadogService) { }

  handleError(error: any): void {
    console.error(error);
    // this._datadog.logger.error(error);
    // throw error
  }
}
